#ifndef COMMANDS_H
	#define COMMANDS_H

//DRAW PIXEL
String DPX_CMD = "DPX";
// DRAW PIC
String DPIC_CMD = "DPIC";
//UPLOAD PIC
String UPIC_CMD= "UPIC";
//LOAD PICTURE FROM SPIFF
String LPIC_CMD= "LPIC";
//WRITE TEXT
String DTXT_CMD = "DTXT";


#endif